// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ConsumerClient is the client API for Consumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsumerClient interface {
	VerifyConsumer(ctx context.Context, in *VerifyConsumerRequest, opts ...grpc.CallOption) (*VerifyConsumerReply, error)
}

type consumerClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerClient(cc grpc.ClientConnInterface) ConsumerClient {
	return &consumerClient{cc}
}

var consumerVerifyConsumerStreamDesc = &grpc.StreamDesc{
	StreamName: "VerifyConsumer",
}

func (c *consumerClient) VerifyConsumer(ctx context.Context, in *VerifyConsumerRequest, opts ...grpc.CallOption) (*VerifyConsumerReply, error) {
	out := new(VerifyConsumerReply)
	err := c.cc.Invoke(ctx, "/proto.Consumer/VerifyConsumer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerService is the service API for Consumer service.
// Fields should be assigned to their respective handler implementations only before
// RegisterConsumerService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type ConsumerService struct {
	VerifyConsumer func(context.Context, *VerifyConsumerRequest) (*VerifyConsumerReply, error)
}

func (s *ConsumerService) verifyConsumer(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.VerifyConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/proto.Consumer/VerifyConsumer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.VerifyConsumer(ctx, req.(*VerifyConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterConsumerService registers a service implementation with a gRPC server.
func RegisterConsumerService(s grpc.ServiceRegistrar, srv *ConsumerService) {
	srvCopy := *srv
	if srvCopy.VerifyConsumer == nil {
		srvCopy.VerifyConsumer = func(context.Context, *VerifyConsumerRequest) (*VerifyConsumerReply, error) {
			return nil, status.Errorf(codes.Unimplemented, "method VerifyConsumer not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "proto.Consumer",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "VerifyConsumer",
				Handler:    srvCopy.verifyConsumer,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "customer.proto",
	}

	s.RegisterService(&sd, nil)
}
