// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SagaClient is the client API for Saga service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SagaClient interface {
	CreateOrderSaga(ctx context.Context, in *CreateOrderSagaRequest, opts ...grpc.CallOption) (*CreateOrderSagaReply, error)
}

type sagaClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaClient(cc grpc.ClientConnInterface) SagaClient {
	return &sagaClient{cc}
}

var sagaCreateOrderSagaStreamDesc = &grpc.StreamDesc{
	StreamName: "CreateOrderSaga",
}

func (c *sagaClient) CreateOrderSaga(ctx context.Context, in *CreateOrderSagaRequest, opts ...grpc.CallOption) (*CreateOrderSagaReply, error) {
	out := new(CreateOrderSagaReply)
	err := c.cc.Invoke(ctx, "/proto.Saga/CreateOrderSaga", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaService is the service API for Saga service.
// Fields should be assigned to their respective handler implementations only before
// RegisterSagaService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type SagaService struct {
	CreateOrderSaga func(context.Context, *CreateOrderSagaRequest) (*CreateOrderSagaReply, error)
}

func (s *SagaService) createOrderSaga(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.CreateOrderSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/proto.Saga/CreateOrderSaga",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.CreateOrderSaga(ctx, req.(*CreateOrderSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterSagaService registers a service implementation with a gRPC server.
func RegisterSagaService(s grpc.ServiceRegistrar, srv *SagaService) {
	srvCopy := *srv
	if srvCopy.CreateOrderSaga == nil {
		srvCopy.CreateOrderSaga = func(context.Context, *CreateOrderSagaRequest) (*CreateOrderSagaReply, error) {
			return nil, status.Errorf(codes.Unimplemented, "method CreateOrderSaga not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "proto.Saga",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "CreateOrderSaga",
				Handler:    srvCopy.createOrderSaga,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "saga.proto",
	}

	s.RegisterService(&sd, nil)
}
