// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TreasurerClient is the client API for Treasurer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TreasurerClient interface {
	AuthorizeCard(ctx context.Context, in *AuthorizeCardRequest, opts ...grpc.CallOption) (*AuthorizeCardReply, error)
}

type treasurerClient struct {
	cc grpc.ClientConnInterface
}

func NewTreasurerClient(cc grpc.ClientConnInterface) TreasurerClient {
	return &treasurerClient{cc}
}

var treasurerAuthorizeCardStreamDesc = &grpc.StreamDesc{
	StreamName: "AuthorizeCard",
}

func (c *treasurerClient) AuthorizeCard(ctx context.Context, in *AuthorizeCardRequest, opts ...grpc.CallOption) (*AuthorizeCardReply, error) {
	out := new(AuthorizeCardReply)
	err := c.cc.Invoke(ctx, "/proto.Treasurer/AuthorizeCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TreasurerService is the service API for Treasurer service.
// Fields should be assigned to their respective handler implementations only before
// RegisterTreasurerService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type TreasurerService struct {
	AuthorizeCard func(context.Context, *AuthorizeCardRequest) (*AuthorizeCardReply, error)
}

func (s *TreasurerService) authorizeCard(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.AuthorizeCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/proto.Treasurer/AuthorizeCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.AuthorizeCard(ctx, req.(*AuthorizeCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterTreasurerService registers a service implementation with a gRPC server.
func RegisterTreasurerService(s grpc.ServiceRegistrar, srv *TreasurerService) {
	srvCopy := *srv
	if srvCopy.AuthorizeCard == nil {
		srvCopy.AuthorizeCard = func(context.Context, *AuthorizeCardRequest) (*AuthorizeCardReply, error) {
			return nil, status.Errorf(codes.Unimplemented, "method AuthorizeCard not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "proto.Treasurer",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "AuthorizeCard",
				Handler:    srvCopy.authorizeCard,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "treasurer.proto",
	}

	s.RegisterService(&sd, nil)
}
